def HowTo4CAL(langage):
    if langage=='JPN':
        tx='''
このアプリでは、SPring-8（BL40B2）での実験で得られる実験データの解析を一括で行うことができます。
事前に、以下のファイルをPCやHDDなどの任意の場所に保存してください。

①chiファイルがまとめられたフォルダー
ログシートにまとめられた全てのchiファイルを一つのフォルダーに保存してください。
必要のないchiファイルがあっても問題ないです。
ログシートでのファイル名が完全に一致しているかどうかは確認してください。
②イオンチャンバーのテキストファイル
透過率や照射時間がまとめられたテキストファイル。ビームラインが生成するものを使用してください。
③ログシート（excelファイル）
GitHub上に公開されている指定のファイルを使用してください。上2行は編集しないでください。
左からサンプルのファイル名、サンプル名、溶媒のサンプル名（溶媒がない場合空白でOK）、絶対散乱強度補正定数（補正を行わない場合は、1と記入）

〜解析後〜
それぞれのサンプルでcsvファイル（'サンプル名'.csv）が生成されます。
q: 散乱ベクトルの絶対値
I: サンプルの観測散乱強度
I_t: 透過率補正後のサンプル散乱強度（I/IC2）
Isol: 溶媒の観測散乱強度
Isol_t: 透過率補正後の溶媒散乱強度（Isol/IC2）
exI: 過剰散乱強度（I_t-Isol_t）
absI: サンプルの絶対散乱強度（exI*絶対散乱強度補正定数）
補正定数、溶媒の未設定の場合、対応するデータはcsvファイルに保存されません。
        
        '''
    if langage=='ENG':
        tx='''
This application allows you to analyze experimental data obtained from experiments at SPring-8 (BL40B2) in a batch.
In advance, please save the following files to any location on your PC or HDD.

(1) "A folder in which the chi files are stored"
Please store all the chi files compiled in the log sheet in a single folder.
It does not matter if there are some chi files you do not need.
Please make sure that the file names in the log sheet are completely consistent.
(2) "Ion chamber text file"
A text file that summarizes transmittance and irradiation time. Please use the one generated by the beamline.
(3) "Log sheet (excel file)"
Please use the specified file on GitHub. Do not edit the top two lines.
From left to right: 'file name of sample', 'sample name', 'sample name of solvent' (if there is no solvent, leave blank), 'absolute scattering intensity correction constant (enter 1 if no correction is made).

~~after analysis~~
A csv file ('sample name'.csv) will be generated for each sample.
q: Absolute value of scattering vector
I: Measured scattering intensity of the sample
I_t: Sample scattering intensity after transmission correction (I/IC2)
Isol: Measured scattering intensity of the solvent
Isol_t: Measured scattering intensity of the solvent after transmission correction (Isol/IC2)
exI: Excess scattering intensity (I_t-Isol_t)
absI: Absolute scattering intensity of the sample (exI*absolute scattering intensity correction constant)
If the correction constant and solvent are not set, the corresponding data will not be saved in the csv file.

        '''
    
    return tx

def HowTo4ABS(langage):
    if langage=='JPN':
        tx='''
このアプリでは、測定条件は25度での絶対散乱強度補正定数を算出します。

補正定数＝0.01632/水の平均散乱強度

この時、0.01632はq範囲（1〜3 nm^-1）における絶対散乱強度である。

アプリでは、選択されたカメラ長に応じて、q範囲が1~3に入るようにしています。
        
        '''
    if langage=='ENG':
        tx='''
This application calculates the absolute scattering intensity correction constant at 25 degrees for the measurement conditions.

Correction constant = 0.01632/average scattering intensity of water

In this case, 0.01632 is the absolute scattering intensity in the q range (1~3 nm^-1).

In the application, the q range is 1~3 depending on the selected camera length.

        '''
    
    return tx

def creator():
    t='''
Shin Takano

Git Hub: https://github.com/Chemtakano
mail: chemtakano@gmail.com
    '''
    return t